blueprint:
  name: room_lights_toogle_and_recall_scenes
  description: Toggle lights for a specific Room
  domain: automation
  input:
    lights_switch:
      name: Input Toggle Switch
      selector:
        entity:
          filter:
            domain: input_boolean
    lights_scene_selector:
      name: Current Scene Selector
      description: The selector which contains all available scenes for the room
      selector:
        entity:
          filter:
            domain: input_select
    lights_scene_default:
      name: First Scene
      description: First scene (default) to be used
      selector:
        state:
          entity_id: input_select.home_scenes
    lights_scene_default_behavior:
      name: Switch-on Scene
      description: Default behavior for the scene to recall when turning lights on
      selector:
        select:
          options:
            - label: Use latest
              value: use_latest
            - label: Use default
              value: use_default


variables:
  lights_switch_entity_id: !input lights_switch
  lights_scene_default_suffix: !input lights_scene_default
  lights_scene_selector: !input lights_scene
  lights_scenes: >
    {{ state_attr(lights_scene_selector, 'options') }}

# If motion is detected within the delay,
# we restart the script.
mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id:
      - !input lights_switch



action:
  - if:
      - condition: state
        entity_id: !input lights_switch
        state: "off"
    then:
      - action: scene.turn_on
        metadata: {}
        target:
          entity_id: scene.{{ lights_switch_entity_id }}_turn_off
    else:
      - choose:
          {% for i in range(0, lights_scenes|length) %}
          - conditions:
              - condition: state
                entity_id: input_select.scene_light_studio_salon
                state: normal
            sequence:
              - action: scene.turn_on
                metadata: {}
                target:
                  entity_id: scene.{{ lights_switch_entity_id }}_{{ lights_scene_default }}
          {% endfor %}
        default:
          - action: scene.turn_on
            metadata: {}
            target:
              entity_id: scene.{{ lights_switch_entity_id }}_turn_on_scn_{{ lights_scene_default }}
